name: Deploys project to Azure 

on:
  push:
    branches:
      - master
      
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:


env:
  DOTNET_VERSION: '3.1.302'  
  
  
  
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SubscriptionId }}
        resourceGroupName: ${{ secrets.AZURE_ResourceGroupName }}
        template: arm/static-webapp.json
        parameters: arm/static-webapp.parameters.json repositoryToken=${{ secrets.AUTHTOKEN }}
